--- 
title: "R Programming Guidebook Project"
author: "Alec Nguyen"
site: bookdown::bookdown_site
bibliography: references.bib
biblio-style: apalike
link-citations: yes
---

# About {-}

Source Code - https://github.com/alecng27/R_Programming_Guidebook

See the [LICENSE](https://github.com/alecng27/R_Programming_Guidebook/blob/main/LICENSE) file for license rights and limitations.

This is my personal guidebook that I created with notes and examples on the workings of R, SQL and Web Scraping. This online book is created and developed using RStudio and the Bookdown package.

This overview provides a brief explanation of this book. This book has two main sections, DataCamp and Econometrics. Each is described below.

The DataCamp section is notes on DataCamp courses. Much of the content in these chapters is directly copy/pasted from DataCamp. Typically this is plagiarism, something important to avoid both at and outside of Lawrence. However, directly copy/pasted content is an important aspect of this BP and it isn’t feasible to put quotation marks around all of it. So, we will give credit where credit is due here. Let this sentence serve as attribution and citation: except for the portions of the DataCamp section that are my own notes supplementing the DataCamp content, which are indicated in red font using the “mynotes” html tag, all content comes directly from DataCamp and the author of this book is giving them credit for their content.

The Econometric section has chapters based on econometrics content covered in Econometrics (ECON 380). Content and data in those sections come from the sources discussed in those chapters. These chapters serve as a reference for important concepts and technical skills, as well as examples of how to implement them in R.

**Author**

Alec Nguyen

Economics & Data Science B.A, Lawrence University

alec.nguyen27@gmail.com

[LinkedIn](https://www.linkedin.com/in/alec-nguyen-about/)

[Project Portfolio](https://alecng27.github.io/Project_Portfolio/)


